[build]
  base = "" # Use the root directory for the base directory
  publish = "build" # Adjust to your output directory
  command = "npm run build" # The build command for your project

[build.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://ti709888:talha1234@opeak.ziauuqy.mongodb.net/opeak"
  TOKEN_LOGIN_USER = "User846niodshf&6"
  CLOUDINARY_CLOUD_NAME = "dxkmxupyw"
  CLOUDINARY_API_KEY = "428879428967335"
  CLOUDINARY_API_SECRET = "oouIijcek-ju-vh387e-l9oCfXM"
  STRIPE_PUBLISHABLE_KEY = "pk_test_51PZTZpRvfySd4cFreXwL9pOIgTB6HcxpiERX3jII9L2f8e6cz0hJZmrogecKIekABJxEUeWJ7MBVEfw2aV16hZNQ00ptEWJcq7"
  STRIPE_SECRET_KEY = "sk_test_51PZTZpRvfySd4cFrRvdPjwVtVbZCB4uuRvydKTU3RDuWymDOdeYtK0YUnXLfiLe8xLRIjSy9cmRT31JQqneLj6Tm00CIBotktX"
  PUBLIC_URL = "http://localhost:3000"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
